// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetImageData(arg1) {
  return window['go']['main']['App']['GetImageData'](arg1);
}

export function GetInitialImage() {
  return window['go']['main']['App']['GetInitialImage']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function ProcessImage(arg1) {
  return window['go']['main']['App']['ProcessImage'](arg1);
}

export function ProcessImageFile(arg1) {
  return window['go']['main']['App']['ProcessImageFile'](arg1);
}
